@echo off
rem ============================================================
rem  v7 one-shot deploy: BuildVersion -> push -> deploy -> verify
rem  Incident_2026-08-24_ManualSales_Deploy_Gap countermeasure B-2.
rem  Usage: deploy.cmd   (run from anywhere; cd's to its own dir)
rem ============================================================
setlocal
cd /d "%~dp0"
set PROD_ID=AKfycbwV8eVN6KJvfMnQLkNmbOqYsjpvQSJTCqk40kfyMFzRjxFItJ8-4VxOV4U9MojLH4U
set CLASP=C:\nodejs-global\clasp.cmd

for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd-HHmmss"') do set BUILD=v7-%%i

echo // AUTO-GENERATED by deploy.cmd - do not edit manually.> BuildVersion.gs
echo // Production check: /exec?action=ping returns this as "build".>> BuildVersion.gs
echo var BUILD_VERSION = '%BUILD%';>> BuildVersion.gs

echo [1/3] clasp push --force
call "%CLASP%" push --force
if errorlevel 1 goto :fail

echo [2/3] clasp deploy to production (@%PROD_ID:~0,12%...)
call "%CLASP%" deploy --deploymentId %PROD_ID% --description "%BUILD%"
if errorlevel 1 goto :fail

echo [3/3] verify production serves %BUILD%
set PING_URL=https://script.google.com/macros/s/%PROD_ID%/exec?action=ping
for /l %%n in (1,1,3) do (
  curl -sL "%PING_URL%" | findstr /c:"%BUILD%" >nul
  if not errorlevel 1 (
    echo OK: production is serving %BUILD%
    exit /b 0
  )
  timeout /t 5 /nobreak >nul
)
echo NG: production ping did not return %BUILD% - deployment NOT verified
exit /b 1

:fail
echo FAILED: clasp push/deploy error
exit /b 1
